config/routes.rb
Rails.application.routes.draw do

  resources :roles
  resources :articles do
    member do
      post :upload_image
      delete :remove_image
    end
  end

  devise_for :users
  root to: 'articles#index'

  resources :users

end

app/models/article.rb
class Article < ActiveRecord::Base
  #require 'carrierwave/orm/activerecord'
  #mount_uploader :image, ImageUploader
  acts_as_taggable_on :tags

  belongs_to :user
  belongs_to :category
  belongs_to :status
  #has_many :tags

  default_scope ->{ where(created_flag: true)}

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  #validates :title, presence: true, uniqueness: true
  #validates :description, presence: true

  def self.clean
    self.unscoped.where(created_flag: false).delete_all
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy, :upload_image]

  respond_to :html
  #load_and_authorize_resource
  def index
    @articles = current_user.articles
    respond_with(@articles)
  end

  def show

    respond_with(@article)

  end

  def new
    @article = Article.create
    respond_with(@article)
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.save
    respond_with(@article)
  end

  def update
    @article.update(article_params)
    Article.clean
    respond_with(@article)
  end

  def destroy
    @article.image = nil
    @article.destroy
    respond_with(@article)
  end

  def upload_image
    @article.image = params[:file]
    @article.save
      respond_to do |format|
        format.json {  render :json => @article }
      end
  end

  def remove_image
    @article = Article.find_by_id params[:id]
    @article.image.destroy
    @article.save
    respond_to do |format|
      format.js
      format.json {  render :json => @article }
    end
  end


  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description, :image, :status_id, :category_id, :user_id, :tag_list, :files, :created_flag)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/articles/_form.html.slim
= simple_form_for @article, :html => { :class => "form-horizontal",  id: "my-awesome-dropzone" } do |f|
  .form
    = f.input :title
    = error_span(@article[:title])
    = render 'layouts/shared/toolbar'
    = f.input :description, input_html:{id: 'description', rows: 10}, placeholder: 'Description....', label: false
    = error_span(@article[:description])
    = f.association :status, label_method: :name, value_method: :id, include_blank: false, prompt: "Choose One.."
    = f.association :category, as: :radio_buttons, label: 'Verticals'
    = simple_form_for @article, :html => {:class => "dropzone"} do |f|
    #drop_zone
      form#fb-drop-zone.dropzone.dz-message action=upload_image_article_path(@article, :remote => true)
    - if @article.image.file?
      #edit_image
        = image_tag @article.image.url(:thumb)
        = link_to 'Remove Image', remove_image_article_path(@article.id), method: :delete, :remote => true
    = f.input :tag_list, input_html: {id: 'tags', value: f.object.tag_list.join(",")}
    = f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id }
    = f.input :created_flag, :as => :hidden, :input_html => { :value => true }
    = error_span(@article[:image])
    = f.button :submit, 'Save', :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), articles_path, :class => 'btn btn-default'

app/views/articles/_verticals.html.slim
= f.association :status, label_method: :name, value_method: :id, include_blank: false, prompt: "Choose One.."

app/views/articles/edit.html.slim
- model_class = Article
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/articles/index.html.slim
- model_class = Article
div class="page-header show-index"
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
table class="table table-striped"
  thead
    tr
      th= model_class.human_attribute_name(:image)
      th= model_class.human_attribute_name(:title)
      th= model_class.human_attribute_name(:description)
      th= model_class.human_attribute_name(:author)
      th= model_class.human_attribute_name(:status)
      th= model_class.human_attribute_name(:verticals)
      th= model_class.human_attribute_name(:tags)
      - if current_user.admin? || current_user.editor?
        th=t '.actions', :default => t("helpers.actions")
  tbody
    - @articles.each do |article|
      tr
        td= image_tag article.image.url(:thumb)
        td= article.title
        td= Sanitize.fragment(article.description)
        td= article.user.full_name
        td= article.status.try(:name)
        td= article.category.try(:name)
        td= article.tags.map{|t| t.name}.join(",")
        td
          - if can? :manage, article
            = link_to t('.edit', :default => t("helpers.links.edit")), edit_article_path(article), :class => 'btn btn-default btn-xs'
            = link_to t('.destroy', :default => t("helpers.links.destroy")), article_path(article), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'
          - elsif can? :edit, article
            = link_to t('.edit', :default => t("helpers.links.edit")), edit_article_path(article), :class => 'btn btn-default btn-xs'

/= link_to t('.new', :default => t("helpers.links.new")), new_article_path, :class => 'btn btn-primary'

app/views/articles/new.html.slim
- model_class = Article
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/articles/remove_image.js.erb
jQuery('form #edit_image img').remove();
jQuery('form #edit_image a').remove();

app/views/articles/show.html.slim
- model_class = Article
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:title) + ':'
  br
  = @article.title

p
  strong= model_class.human_attribute_name(:description) + ':'
  br
  = @article.description.html_safe
p
  strong= model_class.human_attribute_name(:image) + ':'
  br
  = image_tag @article.image.url(:thumb)

= link_to t('.back', :default => t("helpers.links.back")), articles_path, :class => 'btn btn-default'

- if can? :manage, @article
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_article_path(@article), :class => 'btn btn-default'

  = link_to t('.destroy', :default => t("helpers.links.destroy")), article_path(@article), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'
- elsif can? :edit, @article
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_article_path(@article), :class => 'btn btn-default'

app/views/articles/upload_image.js.erb
<% if @status == 'success' %>
    jQuery('form #edit_image img').remove();
    console.log ('here');
    alert ('here');
//    $('#edit_image').html('<%#= image_tag @article.image.url(:thumb)%>')
<% end %>