config/routes.rb
Rails.application.routes.draw do

  resources :roles
  resources :articles do
    member do
      post :upload_image
      delete :remove_image
    end
  end

  devise_for :users
  root to: 'articles#index'

  resources :users

end

app/views/layouts/_header.html.slim
nav.navbar.navbar-default
  .container-fluid
    /! Brand and toggle get grouped for better mobile display
    .navbar-header
      button.navbar-toggle.collapsed data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href="#"  Content Planning
    /! Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav
        li
          = link_to('Write', new_article_path)
        li
          = link_to('Articles', articles_path, :method => :get)
        - if can? :manage, :all
          li
            = link_to('Invite',  new_user_invitation_path, :method => :get)
          /li
          /  = link_to('Create Role', new_role_path, :method => :get)
          /li
          /  = link_to('Assign Role', new_role_path, :method => :get)
          li.dropdown
            a.dropdown-toggle aria-expanded="false" data-toggle="dropdown" href="#" role="button"
              | Roles
              span.caret
            ul.dropdown-menu role="menu"
              li
                = link_to('Create Role', new_role_path, :method => :get)
              li
                = link_to('Users', users_path, :method => :get)
              li
                = link_to('Roles', roles_path, :method => :get)
        /    li.divider
        /    li
        /      a href="#"  Separated link
        /    li.divider
        /    li
        /      a href="#"  One more separated link
      /form.navbar-form.navbar-left role="search"
      /  .form-group
      /    input.form-control placeholder="Search" type="text" /
      /  button.btn.btn-default type="submit"  Submit
      ul.nav.navbar-nav.navbar-right
        /li
        /  = link_to('Logout', destroy_user_session_path, :method => :delete)
          /a href="#{destroy_user_session_path}"  Logout
        li.dropdown
          a.dropdown-toggle aria-expanded="false" data-toggle="dropdown" href="javscript:void(0)" role="button"
            | #{current_user.full_name}
            span.caret
          ul.dropdown-menu role="menu"
            li
              = link_to('Logout', destroy_user_session_path, :method => :delete)
        /    li
        /      a href="#"  Another action
        /    li
        /      a href="#"  Something else here
        /    li.divider
        /    li
        /      a href="#"  Separated link
    /! /.navbar-collapse
  /! /.container-fluid

app/views/layouts/_right_side_bar.hrml.slim
|asdasda

app/views/layouts/_side_bar.html.slim
asdasdasd

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ContentPlanning</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body data-no-turbolink>
<div class="container col-lg-12">
  <% if user_signed_in? %>
      <%= render partial: 'layouts/header' %>
  <% end %>
</div>

    <div class="col-md-3">
      <!--<input id="input-700" name="kartik-input-700" type="file" multiple=true class="file-loading" data-upload-url="/site/file-upload" data-max-file-count="10">-->
    </div>
    <div class="col-md-6">
      <div class="header">

      </div>
      <div class="body">
        <%= yield %>
      </div>
      <div class="footer">

      </div>
    </div>
    <div class="col-md-3">
    </div>

</body>
</html>